### ISSUE TITLE
Ideas for Base Detector

### ISSUE THREAD

**Issue by abdilahrf** [francisconeves97/jxscout-vscode#2]
This a good base detector we should have.
 
- Cookies
- URL paths and parameters
- AJAX/XHR/fetch requests
- postMessage handlers and origins
- Event listeners (especially message events)
- GraphQL queries and mutations
- Local/Session storage access
- DOM manipulation points
- WebSocket connections
- URL fragment handlers
- iframe interactions
- API Keys
- Basic Authtentication

**Comment by francisconeves97** [comment]
Great stuff @abdilahrf! Thanks for your contribution! If you have any specific apis for example for dom manipulation points feel free to add more details

**Comment by abdilahrf** [comment]
There could be a lot scenario in the dom manipulation, but this could be one example

```
rules:
  - id: dom-xss-location-to-document-write
    languages: [javascript, typescript]
    severity: ERROR
    message: DOM-based XSS vulnerability from location to document.write
    metadata:
      category: security
      cwe: "CWE-79: Improper Neutralization of Input During Web Page Generation"
      owasp: "A7:2017-XSS"
      references:
        - https://owasp.org/www-community/attacks/xss/
    mode: taint
    pattern-sources:
      - pattern-either:
          - pattern: location.$PROP
          - pattern: location.$PROP.split($DELIM)[$INDEX]
    pattern-sinks:
      - pattern-either:
          - pattern: document.write($SINK)
          - pattern: document.getElementsByTagName(...).href
    pattern-sanitizers:
      - pattern-either:
          - pattern: DOMPurify.sanitize(...)
    options:
      taint_assume_safe_functions: false
      taint_assume_safe_indexes: false
```

example vuln code
```
var x = location.hash.split("#")[1];
var z = "x";
document.write(x);// vuln
document.write('x'); // safe
// safe
writexx("HARDCODED")
writexx(z)
// vuln
writexx(x)

function writexx(daw){temp=daw;simpan(temp);}
function duar(){ simpan("x");}
function simpan(xaw){
    document.write(xaw);
    document.getElementsByTagName("a").href = xaw;
}

```

<img width="1396" alt="Image" src="https://github.com/user-attachments/assets/623526b7-f9ed-4a74-9a74-de628e2836b2" />
